export const ActionType = {
  LoadGuitars: 'data/loadGuitars',
  LoadGuitarsFilter: 'data/loadGuitarsFilter',
  LoadCurrentGuitar: 'data/loadCurrentGuitar',
  LoadGuitarRequest: 'data/loadGuitarRequest',
  NoLoadingUrl:'data/NoLoadingUrl',
  ChangeSearch: 'user/changeSearch',
  ChangeSortType: 'user/changeSortType',
  ChangeDirectionType: 'user/changeDirectionType',
  ChangeMinPrice: 'user/changeMinPrice',
  ChangeMaxPrice: 'user/changeMaxPrice',
  ChangeTypeFilter: 'user/changeTypeFilter',
  ChangeStringFilter: 'user/changeStringFilter',
  CurrentNumberPage: 'user/currentNumberPage',
  LoadGuitarsPagination: 'user/loadGuitarsPagination',
  SetComments: 'user/SetComments',
};
