export const ActionType = {
  LoadGuitars: 'data/loadGuitars',
  LoadGuitarsFilter: 'data/loadGuitarsFilter',
  LoadCurrentGuitar: 'data/loadCurrentGuitar',
  LoadGuitarsPrice: 'data/loadGuitarsPrice',
  LoadGuitarRequest: 'data/loadGuitarRequest',
  NoLoadingUrl: 'data/noLoadingUrl',
  LoadFilterGuitars: 'data/loadFilterGuitars',
  LoadingGuitarBasket: 'data/loadingGuitarBasket',

  LoadingCurrentGuitar: 'data/loadingCurrentGuitar',
  PostCouponLoading: 'data/postCouponLoading',

  SetGuitarsError: 'data/SetGuitarsError',
  SetErrorNoFound: 'data/setErrorNoFound',
  LoadFilterPricce: 'data/loadFilterPricce',
  SetDiscountGuitar: 'data/setDiscountGuitar',
  SetCouponPostStatus: 'data/setCouponPostStatus',
  SetComments: 'data/setComments',
  SetCommentNew: 'data/setCommentNew',
  SetCommentPostStatus: 'data/setCommentPostStatus',
  ChangeSearch: 'user/changeSearch',
  ChangeSortType: 'user/changeSortType',
  ChangeDirectionType: 'user/changeDirectionType',
  ChangeMinPrice: 'user/changeMinPrice',
  ChangeMaxPrice: 'user/changeMaxPrice',
  ChangeTypeFilter: 'user/changeTypeFilter',
  ChangeStringFilter: 'user/changeStringFilter',
  CurrentNumberPage: 'user/currentNumberPage',
  LoadGuitarsCountPagination: 'user/loadGuitarsCountPagination',
  SetModalType: 'user/setModalType',
  SetGuitarAddModal: 'user/setGuitarAddModal',
  SetGuitarAddBasket: 'user/setGuitarAddBasket',
  SetGuitarIdAndCount: 'user/setGuitarIdAndCount',
};
