export const ActionType = {
  LoadGuitars: 'data/loadGuitars',
  LoadGuitarsFilter: 'data/loadGuitarsFilter',
  LoadCurrentGuitar: 'data/loadCurrentGuitar',
  LoadGuitarsPrice: 'data/loadGuitarsPrice',
  LoadGuitarRequest: 'data/loadGuitarRequest',
  NoLoadingUrl: 'data/noLoadingUrl',
  LoadFilterGuitars: 'data/loadFilterGuitars',
  LoadingCurrentGuitar: 'data/loadingCurrentGuitar',
  SetGuitarsError: 'data/SetGuitarsError',
  ChangeSearch: 'user/changeSearch',
  ChangeSortType: 'user/changeSortType',
  ChangeDirectionType: 'user/changeDirectionType',
  ChangeMinPrice: 'user/changeMinPrice',
  ChangeMaxPrice: 'user/changeMaxPrice',
  ChangeTypeFilter: 'user/changeTypeFilter',
  ChangeStringFilter: 'user/changeStringFilter',
  CurrentNumberPage: 'user/currentNumberPage',
  LoadGuitarsCountPagination: 'user/loadGuitarsCountPagination',
  SetComments: 'data/setComments',
  SetCommentNew: 'data/setCommentNew',
  SetCommentPostStatus: 'data/setCommentPostStatus',
  SetModalType: 'user/setModalType',


};
