import { GuitarTypeEng } from '../const';

export const mockGuitar = {
  id: 1,
  name: 'Честер Bass',
  vendorCode: 'SO757575',
  type: GuitarTypeEng.Electric,
  description: 'Замечательный малобюджетный вариант, созданный для новичков, которые отдают предпочтение мелодичным стилям. Прекрасно звучат блюз и баллады, исполненные на этой гитаре. Акустические свойства весьма высоки, в отличие от ее стоимости.',
  previewImg: 'img/guitar-1.jpg',
  stringCount: 7,
  rating: 4,
  price: 17500,
  comments: [],
};

export const mockGuitars = [
  {
    id: 1,
    name: 'Честер Bass',
    vendorCode: 'SO757575',
    type: GuitarTypeEng.Electric,
    description: 'Замечательный малобюджетный вариант, созданный для новичков, которые отдают предпочтение мелодичным стилям. Прекрасно звучат блюз и баллады, исполненные на этой гитаре. Акустические свойства весьма высоки, в отличие от ее стоимости.',
    previewImg: 'img/guitar-1.jpg',
    stringCount: 7,
    rating: 4,
    price: 17500,
    comments: [],
  },
  {
    id: 2,
    name: 'CURT Z300',
    vendorCode: 'TK129049',
    type: GuitarTypeEng.Acoustic,
    description: 'Эргономичность гитары и качество сборки являются, пожалуй, её главными преимуществами. Идеальное расположение в руках музыканта дополняется прочностью конструкции из клёна.',
    previewImg: 'img/guitar-8.jpg',
    stringCount: 7,
    rating: 3.5,
    price: 29500,
    comments: [],
  },
  {
    id: 3,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },
  {
    id: 4,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },
  {
    id: 5,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },
  {
    id: 6,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },
  {
    id: 7,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },
  {
    id: 8,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },
  {
    id: 9,
    name: 'Roman LX',
    vendorCode: 'RO111111',
    type: GuitarTypeEng.Ukulele,
    description: 'Укулеле класса премиум от компании CURT, собравшая в себе все самые необходимые качесва: лёгкость корпуса, прочность струн и компактный размер.',
    previewImg: 'img/guitar-6.jpg',
    stringCount: 4,
    rating: 4,
    price: 6800,
    comments: [],
  },

];
